service: zero-x-api

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    ZERO_X_API_KEY: ${env:ZERO_X_API_KEY}

functions:
  getQuote:
    handler: handler.handler
    events:
      - http:
          path: /quote
          method: get
          cors: true

package:
  patterns:
    - handler.js
